subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: debian+ca-certificate-rpi64
version: 1.0.0
$version: 1.0.0
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: ca-certificates packaging
  long: ''
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    vanrossum+python3:
      - version: ''
        architecture: []
    openssl+openssl:
      - version: ''
        architecture: []
bump:
  - carnotzet+os-rpi4b
  - carnotzet+os-rpiz2w
data:
  get:
    uri: 'https://salsa.debian.org/debian/ca-certificates/-/archive/<THIS.DATA.GET.REF>/ca-certificates-<THIS.DATA.GET.REF>.tar.gz'
    mirrors: []
    ref: ba3830faf6207f6444827209915dcfc4ce44b272
    $ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 1.0.0@3348db871ac991aa6eb5d9ec9f2343c6d190491e17894ca3700afa445699400b.tar.gz
  type: src
  configure: ''
  rules:
    type: script
    location: data/ca-certificates-<THIS.DATA.GET.REF>
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !python3 -m venv venv
         && . venv/bin/activate
         && pip3 install cryptography
         && make -C mozilla
      maketest: ''
      makeinstall: |-
        !make -C mozilla install CERTSDIR=<PEON.PREFIXDIR.X+BIN>/ssl/certs
         && openssl rehash <PEON.PREFIXDIR.X+BIN>/ssl/certs
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
