subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: linux+util-linux-rpi64
version: 2.41.1
$version: 2.41.1
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Package of utilities distributed by the Linux Kernel Organization
  long: ''
dependency:
  install:
    gnu+libncurses-rpi64:
      - version: ''
        architecture: []
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
bump:
  - carnotzet+os-rpi4b
  - carnotzet+os-rpiz2w
  - carnotzet+os-contelia-rpiz2w
  - carnotzet+rescuefs-rpi4b
  - carnotzet+rescuefs-rpiz2w
  - carnotzet+rescuefs-contelia-rpiz2w
data:
  get:
    uri: 'https://www.kernel.org/pub/linux/utils/util-linux/v2.41/util-linux-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 2.41.1@c756213ed3f17b74c1525fc0ed839d6d09f1731ee443e2415c42071afed58ff9.tar.gz
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=/usr
                     --build=$MACHTYPE
                     --host=aarch64-xcraft-linux-gnu
                     --enable-static
                     --disable-shared
                     --disable-all-programs
                     --enable-libuuid
                     --enable-libsmartcols
                     --enable-libfdisk
                     --enable-fdisks
  rules:
    type: make
    location: data/util-linux-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: install DESTDIR=<PEON.INSTALLDIR.X+BIN>
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
  deploy: |-
    !  rm -rf <PEON.INSTALLDIR.X+BIN>/usr/include
    && rm -rf <PEON.INSTALLDIR.X+BIN>/usr/lib/pkgconfig
    && rm  -f <PEON.INSTALLDIR.X+BIN>/usr/lib/*.a
    && rm  -f <PEON.INSTALLDIR.X+BIN>/usr/lib/*.la
    && rm -rf <PEON.INSTALLDIR.X+BIN>/usr/share/man/man3
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
