subpackage:
  - runtime*
name: gnu+libncurses-rpi64
version: 6.6
$version: 6.6
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: The ncurses library is a free software emulation of curses
  long: |-
    The ncurses (new curses) library is a free software emulation of curses in
    System V Release 4.0 (SVr4), and more. It uses terminfo format, supports
    pads and color and multiple highlights and forms characters and function-key
    mapping, and has all the other SVr4-curses enhancements over BSD curses.
    SVr4 curses became the basis of X/Open Curses.
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
data:
  get:
    uri: 'http://ftpmirror.gnu.org/ncurses/ncurses-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    out: ''
    externals: true
    prepare: ''
    $hash: 6.3@97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059.tar.gz
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=/usr
                     --build=$MACHTYPE
                     --host=aarch64-xcraft-linux-gnu
                     --enable-static
                     --enable-shared
                     --disable-db-install
                     --enable-pc-files
                     --without-shared
                     --without-ada
                     --without-cxx-shared
                     --without-manpages
                     --without-progs
                     --without-tack
                     --without-tests
                     --without-debug
                     --without-profile
                     --without-termlib
                     --without-ticlib
                     --without-gpm
                     --without-dlsym
                     --without-pcre2
                     --without-sysmouse
                     --without-develop
  rules:
    type: script
    location: data/ncurses-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '!make -j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: '!make install DESTDIR=<PEON.INSTALLDIR>'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
      PKG_CONFIG_PATH: ''
      PKG_CONFIG_LIBDIR: '/usr/lib/pkgconfig'
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
